name: Python app

on:
  push:
   branches: [ main ]
  pull_request:
    branches: [ dev1 ]
      
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build & Push Image
      run: |
        echo "${{ secrets.S_KEY }}" | docker login -u "yigdrassil" --password-stdin
        docker image build -t yigdrassil/fastapi:latest .
        docker push yigdrassil/fastapi:latest
